version: '3.7'

services:
  front:
    image: front
    ports:
      - 5000:5000
    networks:
      - net
    environment:
      ADD_BACK: user
    restart: on-failure
    
  user:
    image: user
    networks:
      - net
    ports:
      - 5001:5001
    environment:
      MYSQL_HOST: db
    restart: on-failure

  db-test:
    image: mysql:5.7.36
    volumes:
      - ./mysql-load-test:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: annuaire
      MYSQL_USER : user
      MYSQL_PASSWORD : password
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    networks:
      - net
    ports:
      - 3307:3306

networks:
    net: { }