version: '3.7'

services:
  front:
    image: front
    ports:
      - 10.10.0.2:5000:5000
    networks:
      - front-network
    environment:
      ADD_BACK: user
    restart: on-failure

  user:
    image: user
    networks:
      - back-network
    ports:
      - 10.20.0.2:5001:5001
    environment:
      MYSQL_HOST: db
    restart: on-failure

  db-test:
    image: mysql:5.7.36
    volumes:
      - ./mysql-load-test:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: annuaire
      MYSQL_USER : user
      MYSQL_PASSWORD : password
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    networks:
      - db-network
    ports:
      - 10.30.0.2:3307:3306

networks:
  front-network:
    driver: bridge-front
  back-network:
    driver: bridge-back
  db-network:
    driver: bridge-bdd