version: '2.4'

services:
  front:
    image: front
    networks:
      vlan:
        ipv4_address: 10.10.0.2
    ports:
      - 5000:5000
    environment:
      ADD_BACK: user
    restart: on-failure

  user:
    image: user
    networks:
      vlan:
        ipv4_address: 10.20.0.2
    ports:
      - 5001:5001
    environment:
      MYSQL_HOST: db
    restart: on-failure

  db:
    image: mysql:5.7.36
    volumes:
      - ./mysql-load-test:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: annuaire
      MYSQL_USER : user
      MYSQL_PASSWORD : password
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    networks:
      vlan:
        ipv4_address: 10.30.0.2
    ports:
      - 10.30.0.2:3307:3306

networks:
  front-network:
    name: front-network
    driver: macvlan
    driver_opts:
      parent: ens224
    ipam:
      config:
        - subnet: "10.10.0.0/24"
          gateway: "10.10.0.1"
  back-network:
    name: back-network
    driver: macvlan
    driver_opts:
      parent: ens160
    ipam:
      config:
        - subnet: "10.20.0.0/24"
          gateway: "10.20.0.1"
  db-network:
    name: db-network
    driver: macvlan
    driver_opts:
      parent: ens192
    ipam:
      config:
        - subnet: "10.30.0.0/24"
          gateway: "10.30.0.1"